version: '3.7'

services:
  web:
    hostname: web
    build: ./app
    command: gunicorn budgeteer.wsgi:application --bind "0.0.0.0:8000"
    volumes: # TODO: find out why fedoraCoreOS needs this syntax for nginx to read files correctly
      - type: volume
        source: static_volume
        target: /home/app/web/static
    expose:
      - 8000
    env_file:
      - ./app/.env
    depends_on:
      - db
  # FIXME: we're running the container as root :O
  db:
    hostname: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/.env
  nginx:
    hostname: nginx
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 1337:80
    depends_on:
      - web
    restart: unless-stopped

  pgadmin4:
    hostname: pgadmin4
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - 5050:80
    env_file:
      - ./app/.env
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  # add volume for pgadmin, so that it saves credentials for the db