version: '3.7'

services:
  web:
    build: ./app
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    ports:
      - 8000:8000
    env_file:
      - ./app/.env
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  # db:
  #   image: mariadb:10.1
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     MYSQL_USER: "hello_django"
  #     MYSQL_PASSWORD: "hello_django"
  #     MYSQL_ROOT_PASSWORD: "docker-root"
volumes:
  postgres_data: