# Generated by Django 2.2.4 on 2019-11-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_auto_20190928_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='text',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='text',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='monthlybudget',
            unique_together={('category', 'date')},
        ),
    ]
