# Generated by Django 2.2.4 on 2019-12-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_auto_20191101_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField(unique=True)),
            ],
        ),
    ]
