# Generated by Django 2.2.8 on 2019-12-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_auto_20191204_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybalance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='monthlybalance',
            unique_together={('category', 'date')},
        ),
    ]
