# Generated by Django 2.2.13 on 2020-08-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0010_auto_20200412_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='text',
            field=models.CharField(default=None, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='monthlybalancecategory',
            name='text',
            field=models.CharField(default=None, max_length=70, unique=True),
        ),
    ]
