# Generated by Django 2.2.13 on 2020-08-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0011_auto_20200802_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='text',
            field=models.CharField(default=None, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='text',
            field=models.CharField(default=None, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='monthlybalancecategory',
            name='text',
            field=models.CharField(default=None, max_length=40, unique=True),
        ),
    ]
