# Generated by Django 2.2.13 on 2020-08-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0017_auto_20200829_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybalancecategory',
            name='text',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddConstraint(
            model_name='monthlybalancecategory',
            constraint=models.UniqueConstraint(fields=('text', 'created_by'), name='cat-per-user'),
        ),
    ]
