# Generated by Django 2.2.13 on 2020-08-30 03:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0019_auto_20200829_0903'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='cat-per-user',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('text', 'created_by')},
        ),
    ]
