# Generated by Django 2.2.13 on 2020-08-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0020_auto_20200830_0331'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('text', 'created_by'), name='cat-per-user'),
        ),
    ]
