# Generated by Django 2.2.4 on 2019-09-28 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='spended_date',
            new_name='date',
        ),
    ]
