# Generated by Django 2.2.4 on 2019-08-10 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='text',
            field=models.CharField(default=None, max_length=20, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
