# Generated by Django 2.2.4 on 2019-08-10 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_auto_20190810_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.CharField(default='', max_length=150, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
