# Generated by Django 2.2.4 on 2019-12-04 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_monthlybalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBalanceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=None, max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='monthlybalance',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgets.MonthlyBalanceCategory'),
        ),
    ]
