# Generated by Django 2.2.8 on 2020-01-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_category_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('text', models.CharField(default=None, max_length=20, unique=True)),
                ('note', models.CharField(default=None, max_length=50, unique=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
    ]
