# Generated by Django 2.2.8 on 2020-04-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0008_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybalancecategory',
            name='is_diff_currency',
            field=models.BooleanField(default=False),
        ),
    ]
