- hosts: all

  tasks:
    - name: Forcefully checkout master branch from repo
      git:
        repo: https://github.com/MicheleV/budgeteer.git
        dest: /home/{{ ansible_ssh_user }}/budgeteer
        version: deployment
        force: yes

    - name: Create serving directory
      file:
        path: /home/{{ ansible_ssh_user }}/budgeteer/static
        state: directory
        mode: 0755

    - name: Set facl permissions
      acl:
        path: /home/{{ ansible_ssh_user }}/budgeteer/static
        entry: user:nginx:rwx
        state: present

    # TODO start django

    - name: Put nginx config file in place
      template: src=./nginx.conf.j2 dest=/etc/nginx/conf.d/budgeteer.conf
      notify:
        - restart nginx

  handlers:
      - name: restart nginx
        service:
          name: nginx
          state: restarted
