- hosts: all

  vars:
    epelReleaseMajorVersion: 7

  tasks:

    - name: Update hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Add epel repo
      yum_repository:
        name: epel_repo
        description: EPEL YUM repo
        baseurl:  http://dl.fedoraproject.org/pub/epel/{{epelReleaseMajorVersion}}/x86_64/
        gpgcheck: yes
        gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
        enabled: yes

    - name: Ensure git, python 3.6, development tools and nginx are installed
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - git
          - python36
          - wget
          - gcc
          - make
          - nginx

    - name: Install virtualenv via pip
      pip:
        name: virtualenv
        executable: pip3

    - name: Enable service nginx and ensure it is not masked
      systemd:
        name: nginx
        enabled: yes
        masked: no

    # TODO install firewalld and open port 8000

    - name: Ensure latest version of nss, curl and libcurl are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: true
      become: true
      vars:
        packages:
          - nss
          - curl
          - libcurl

    - name: Copy script to update sqlite3 to 3.29 (Django 2.2 requires 3.8.3+)
      copy: 
        src: update_sqlite3.sh
        dest: /home/{{ ansible_ssh_user }}/
        mode: 0700
        owner: "{{ ansible_ssh_user }}"
      changed_when: False

    - name: Execute the script
      shell: /home/{{ ansible_ssh_user }}/update_sqlite3.sh {{ ansible_ssh_user }}
      become_user: "{{ ansible_ssh_user }}"
      register: execute_sqlite_update
      changed_when: '"Install sqlite3" in execute_sqlite_update.stdout'

    - name: Remove the script to update sqlite3
      file:
        path: /home/{{ ansible_ssh_user }}/update_sqlite3.sh
        state: absent
      changed_when: False

    - name: set selinux flags
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
